Лекция3
m-chugaev/teach-web pull request #20
Opened 2024-02-02 21:56 UTC by Artemcik1

2024-02-03 14:34 UTC, m-chugaev requested changes
Честно говоря, это немного по-читерски. Ожидалось, что будут указаны реальные примеры значений свойств. В случае с font все потенциальные свойства, в случае с background и flex так же. opacity так же имеет чёткие числовые значения о 0 до 1, то есть указать там 0, 0.5 и 1 было бы корректнее чем текущие.

Укажи, пожалуйста реальные примеры из вёрстки, которые часто будут использоваться. Постарайся убрать значения inherit и initial, это исключения которые могут быть для каждого свойства. Ещё есть none и unset, которые тоже не желательно использовать в текущем задании.

2024-02-04 19:09 UTC, Artemcik1 commented
Понял

2024-02-06 22:05 UTC, ErorrHav commented
Вот, исправил

2024-02-07 15:11 UTC, Artemcik1 commented
Еще вопрос 1 возник, если я сделаю задание из README (для продвинутой группы), то я могу на занятия не ходить?

2024-02-08 13:05 UTC, m-chugaev approved these changes

2024-02-08 13:05 UTC, merged