Spesivtsev Vladimir
m-chugaev/teach-web pull request #9
Opened 2024-01-30 06:15 UTC by breaz1

2024-01-31 11:18 UTC, m-chugaev requested changes

2024-01-31 11:18 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +    <link rel="stylesheet" href="../../../style.css"></linkrel>
Я добавил базовые стили для страницы, можешь подключить их тут вместо этих, путь ../style.css

2024-01-31 11:18 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +    <h2>Спесивцев</h2>
Необходимо сделать свою личную секцию, не просто контент в body. Как в шаблоне lecture02/advanced/chugaev/index.html  
Это понадобится для разделения секций на общей странице

2024-01-31 11:18 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/graph.jpg
Картинка должна быть белой и сливаться с фоном, а у тебя синяя)))

2024-01-31 11:18 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +         function changeContent(tabText, jobTitle, salary) {
Просьба отформатировать функцию, чтобы её было удобнее читать

2024-01-31 11:18 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +        document.getElementById('jobTitle').textContent = jobTitle;
В целом решение ок, но нужно менять больше контента, точно как на примере из хабра. И попробуй сделать более уникальные селекторы, чтобы случайно не поменять контент в чужих секциях

2024-01-31 11:18 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +                                <span title="32% специалистов получают премию">
Добавь к блоку cursor pointer или help

2024-01-31 11:18 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +                <button class="main-inf-top-button">
Добавь к кнопке cursor pointer

2024-01-31 11:18 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +                <img class="main-inf-grapgh" src="./graph.jpg" alt="график" />
Сделай так, чтобы картинка не растягивалась во всю ширину, очень странно смотрится)

2024-01-31 11:18 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +    <style>
Если есть желание, попробуй через расширение perfect pixel сверить результат)  
Это не обязательное требование у меня, но на работе часто обязательное.

2024-01-31 11:22 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +                <button class="tabs-col-button" onclick="changeContent('Lead', 'Lead', '358k')">Lead<span style="font-weight: 700;">358k</span></button>
Когда меняешь текст у тебя должна оставаться фраза Фронтенд разработчик после грейда

2024-01-31 11:40 UTC, breaz1 commented on lecture02/advanced/spesivtsev/index.html
> +    <style>
Да я знаю что это, просто макета нет нормального, тяжеловато верстать.

2024-01-31 12:29 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +    <style>
Есть реальный пример, можно сделать скрин)  
https://career.habr.com/salaries?spec_aliases[]=frontend&qualification=Middle

2024-01-31 12:31 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +        .salart-block{
У тебя тут довольно неуникальные названия классов. Если я подключу эту секцию в общий файл, то некоторые другие секции могут сломаться. Тебе нужно придумать как сделать так, чтобы стили работали только в рамках твоей секции, а не в рамках всей страницы. Можно пользоваться вложенными селекторами для новых браузеров (https://tproger.ru/articles/5-novyh-funkcij-css--kotorye-vy-obyazany-znat-v-2024-godu)

2024-02-18 14:05 UTC, m-chugaev commented
![Screenshot 2024-02-18 at 17 04 52](https://github.com/m-chugaev/teach-web/assets/85513989/7c3c7386-9f97-4b0b-b3aa-5900cbbaba1c)
Это даже не близко к макету. Такую работу я не приму

2024-02-18 14:05 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +    <link rel="stylesheet" href="../../../style.css"></linkrel>
проблема актуальна

2024-02-18 14:06 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +    <h2>Спесивцев</h2>
h2 до сих пор не в секции

2024-02-18 14:07 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +        document.getElementById('jobTitle').textContent = jobTitle;
до сих пор актуально, и id использовать не очень, потому что всё сломается, если я добавлю эту секцию на общую страницу.

2024-02-18 14:07 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +                                <span title="32% специалистов получают премию">
блок вообще пропал

2024-02-18 14:08 UTC, m-chugaev commented on lecture02/advanced/spesivtsev/index.html
> +                <img class="main-inf-grapgh" src="./graph.jpg" alt="график" />
картинка вообще пропала

2024-02-21 15:42 UTC, k3zzz1 commented
Мне не понятно поведение, почему при загрузке через live server у меня не отрисовывается блок определенный, в котором даже js функционал не присутствует. Если запускать отдельно без него, то корректно отрабатывает все.

2024-02-21 16:01 UTC, m-chugaev approved these changes

2024-02-21 16:03 UTC, merged